definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
  email: &email
    email:
      recipients:
        - rudrankriyam@gmail.com
      notify:
        success: true
        failure: true
workflows:
  musadorakit:
    name: MusadoraKit Workflow
    environment:
      xcode: 26.0
      vars:
        XCODE_SCHEME: "MusadoraKit"
        APP_ID: "Musadora"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
    triggering:
      <<: *events
    scripts:
      - name: Build Framework
        script: |
          #!/bin/zsh

          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 15" "platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS" "platform=visionOS Simulator,name=Apple Vision Pro")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              xcodebuild clean build \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation
          done
      - name: Test Framework
        script: |
          #!/bin/zsh
          
          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 15" "platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS" "platform=visionOS Simulator,name=Apple Vision Pro")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              set -o pipefail
              xcodebuild clean test \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation | xcpretty --report junit
          done
        test_report: build/reports/junit.xml
    publishing:
      <<: *email
  docc-deployment:
    name: Deploy DocC Documentation
    max_build_duration: 30
    environment:
      xcode: 16.4
      vars:
        XCODE_SCHEME: "MusadoraKit"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Build DocC Documentation
        script: |
          echo "Building DocC documentation for MusadoraKit..."
          swift package generate-documentation --target MusadoraKit \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path MusadoraKit \
            --output-path ./docs
          
          echo "Documentation built successfully!"
          ls -la ./docs
    publishing:
      github_pages:
        source: docs
      <<: *email
